import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../styles/fontawesome.css";
import "../styles/themify-icons.css";
import "../styles/animate.css";
import "../styles/cursor.css";
import "../styles/custom-font.css";
import "../styles/main.css";
import "../styles/ecommerce.css";
import "../styles/premium-animations.css";
import { CartProvider } from "../contexts/CartContext";
import { UserProvider } from "../contexts/UserContext";
import WhatsAppFloatingButton from "../components/WhatsAppFloatingButton/WhatsAppFloatingButton";
import MailFloatingButton from "../components/MailFloatingButton/MailFloatingButton";
import MobileBottomNav from "../components/MobileBottomNav/MobileBottomNav";
import GlobalErrorHandler from "../components/GlobalErrorHandler/GlobalErrorHandler";

export const metadata: Metadata = {
  title: "Innomax - Technology & IT Startup Next Js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100..900;1,100..900&family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Early error handler to catch AbortErrors before React loads
              (function() {
                const isAbortError = (error) => {
                  return error?.name === 'AbortError' ||
                         (error?.name === 'DOMException' && error?.code === 20) ||
                         error?.message?.includes('aborted') ||
                         error?.message?.includes('signal is aborted') ||
                         error?.message?.includes('abort') ||
                         error?.code === '20' ||
                         error?.code === 20 ||
                         (typeof error === 'string' && error.includes('aborted'));
                };
                
                // Handle unhandled promise rejections
                window.addEventListener('unhandledrejection', function(event) {
                  if (isAbortError(event.reason)) {
                    event.preventDefault();
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                    return false;
                  }
                }, true);
                
                // Handle runtime errors
                window.addEventListener('error', function(event) {
                  if (isAbortError(event.error)) {
                    event.preventDefault();
                    event.stopPropagation();
                    event.stopImmediatePropagation();
                    return false;
                  }
                }, true);
              })();
            `,
          }}
        />
      </head>
      <body id='scrool'>
        <GlobalErrorHandler />
        <UserProvider>
          <CartProvider>
            {children}
            <WhatsAppFloatingButton />
            <MailFloatingButton />
            <MobileBottomNav />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
